name: Scheduled Generate Calls

on:
  schedule:
    # UK Prime Time
    - cron: '0 19 * * *'   # 08:00 PM UK (UTC)
    - cron: '0 21 * * *'   # 10:00 PM UK (UTC)

    # US EST Prime Time
    - cron: '0 1 * * *'    # 08:00 PM EST
    - cron: '0 3 * * *'    # 10:00 PM EST

    # US PST Prime Time
    - cron: '0 5 * * *'    # 10:00 PM PST
    - cron: '0 6 * * *'    # 11:00 PM PST

jobs:
  call_generate_endpoints:
    runs-on: ubuntu-latest
    steps:
      - name: Call both generate routes
        run: |
          echo "Calling hindi-yt route..."
          curl -s https://hindi-yt.onrender.com/generate

          echo "Calling instagram-dm-hnb6 route..."
          curl -s https://instagram-dm-hnb6.onrender.com/generate
