name: Scheduled america Generate Calls

on:
  schedule:
    # U.S. YouTube peak hours (in UTC)
    - cron: '0 6 * * *'    # 1:00 AM EST
    - cron: '0 12 * * *'   # 7:00 AM EST
    - cron: '0 17 * * *'   # 12:00 PM EST
    - cron: '0 20 * * *'   # 3:00 PM EST
    - cron: '0 0 * * *'    # 7:00 PM EST
    - cron: '0 3 * * *'    # 10:00 PM EST

jobs:
  call_generate_endpoint:
    runs-on: ubuntu-latest
    steps:
      - name: Call Render generate route
        run: curl -s https://created-xtl2.onrender.com/generate
