name: Scheduled Generate Calls

on:
  schedule:
    # India Standard Time slots (converted to UTC)
    - cron: '30 3 * * *'   # 09:00 AM IST
    - cron: '30 5 * * *'   # 11:00 AM IST
    - cron: '0 9 * * *'    # 02:30 PM IST
    - cron: '0 12 * * *'   # 05:30 PM IST
    - cron: '30 14 * * *'  # 08:00 PM IST
    - cron: '0 16 * * *'   # 09:30 PM IST

jobs:
  call_generate_endpoint:
    runs-on: ubuntu-latest
    steps:
      - name: Call Render generate route
        run: curl -s https://hindi-yt.onrender.com/generate
