name: Scheduled Generate Calls

on:
  schedule:
    # USA Prime Times (converted to UTC)
    - cron: '0 23 * * *'   # 06:00 PM EST
    - cron: '30 0 * * *'   # 07:30 PM EST / 04:30 PM PST
    - cron: '0 1 * * *'    # 08:00 PM EST / 05:00 PM PST
    - cron: '30 2 * * *'   # 09:30 PM EST / 06:30 PM PST
    - cron: '0 4 * * *'    # 08:00 PM PST (late night EST)

jobs:
  call_generate_endpoint:
    runs-on: ubuntu-latest
    steps:
      - name: Call Render generate route
        run: curl -s https://hindi-yt.onrender.com/generate
